### ISSUE TITLE
Completad descripción del juego y funcionalidad para el 20 de abril (Hito)

### ISSUE THREAD

**Issue by raquelcedazo** [aigora/twQ103_1920-twq103-virtual-life#1]
Hola:

Os comento lo que veo de vuestra primera entrega y os propongo el desarrollo de más funcionalidad.

El menú es bastante básico y me resulta complicado saber cuál es el alcance de vuestro trabajo, puesto que además en el archivo README no habéis completado las funcionalidades con detalle en los "Objetivos del trabajo". Por favor, ampliadme la información.

El hito que os propongo para el 20 de abril es que creéis un fichero con todos los usuarios del juego y hagáis el login en la aplicación, por medio de las opciones del menú. Os aconsejo que almacenéis los datos en un vector de estructuras.

Además de esto, os animo a que sigáis programando más funcionalidades.

Un saludo y buenas vacaciones.

**Comment by gemafrutos** [comment]
Ya hemos cambiado un poco más los objetivos del trabajo. Además al avanzar más en el código del juego para darle una funcionalidad creemos que ya se puede intuir de que va(gracias a las instrucciones y ya al apartado donde comienza el juego con las preguntas).

Respecto a la parte de iniciar sesión y crear usuario no terminamos de saber como guardar el usuario si primeros tenemos que comprobar si hay alguno repetido... es lo único que de momento nos falla y no encontramos solución.

**Comment by raquelcedazo** [comment]
Respecto a los usuarios. Si el usuario selecciona darse de alta, el programa debe comprobar si ya existe el usuario (en base a unos criterios: mismo nickname, mismo correo electrónico, ...). Si ya existe se le muestra un mensaje de error y se le vuelve a mostrar el menú de opciones.
Si no existe, el usuario se añadirá al vector de estructuras y se le vuelve a mostrar el menú de opciones.
Todo debéis hacerlo trabajando en vuestro vector de estructuras. Al comienzo del programa, cargáis los datos del fichero al vector. Y antes de salir del programa, se vuelvan los datos del vector al fichero.

**Comment by raquelcedazo** [comment]
Os vuelvo a abrir la issue hasta que no completéis la funcionalidad.

**Comment by gemafrutos** [comment]
Lo que no sabemos es como cargarlo al vector estructuras ese usuario después de comprobar que no se parece a ningún otro. Lo que hacemos es comparar el que mete el usuario( en una variable de tipo char) con todos los usuarios ya cargados en el vector de estructuras. Y si nos sale que no se parece deberíamos añadirlo, pero no sabemos si con un strcpy o como, ya que de primeras no vamos a añadirlo directamente al vector cuando le preguntamos al usuario porque aún no hemos visto si se parece a otro...

**Comment by raquelcedazo** [comment]
Hay varias formas de poner los datos del usuario en el último lugar del vector.

1) Copiar la estructura del nuevo alumno en una variable:
vector[ultima] = nuevoAlumno;
2) Copiar campo a campo los datos del nuevo alumno:
vector[ultima].matricula = matriculaIntroducida;
strcpy(vector[ultima].nombre, nombreIntroducida);

Saludos

**Comment by IracheAstiz** [comment]
Hemos añadido preguntas, y como ya te hemos comentado hemos hecho la parte de ficheros y del inicio de sesión y usuarios.
